// react-query keys
export const queryKeys = {
  BOTS: 'BOTS',
  USER: 'USER',
  FLOW: 'FLOW',
  NODE: 'NODE',
  LOGIN: 'LOGIN',
  SIGN_UP: 'SIGN_UP',
  CARD_TYPE: 'CARD_TYPE',
  CREATE_BOT: 'CREATE_BOT',
  DELETE_BOT: 'DELETE_BOT',
  CREATE_CARD: 'CREATE_CARD',
  CREATE_NODE: 'CREATE_NODE',
  CHANGE_POSITION: 'CHANGE_POSITION',
};
